const router = require('express').Router()
const Controller = require('../controllers/buyer-controller')

router.get("/", Controller.buyerHome)
router.post("/",Controller.loginPost)
router.get("/add-profile", Controller.addProfile)
router.post("/add-profile", Controller.addProfilePost)
router.get("/dashboard", Controller.buyerDashboard)
router.get("/profile/edit", Controller.editProfile)
router.post("/profile/edit", Controller.editProfilePost)
router.get("/cart", Controller.cart)
router.get("/productdetail/:id", Controller.productDetail)
router.get("/checkout", Controller.checkout)
router.get("/payment", Controller.payment)
router.get("/transactions", Controller.transactions)
router.post("/payment", Controller.paymentPost)
module.exports = router